openapi: 3.0.2
info:
  title: Player Character API
  description: >
    This API definition describes a Player Character API.
  version: 1.1.1
  contact:
    name: API Support
    url: 'http://www.example.com/support'
    email: georgehbroadhurst@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /player-characters:
    get:
      summary: Get all player characters
      operationId: listPlayerCharacters
      tags:
        - Player Character
      responses:
        '200':
          description: A list of player characters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./components/schemas/PlayerCharacter.yaml
  /player-characters/{playerCharacterId}:
    get:
      summary: Get a specific player character by ID
      operationId: getPlayerCharacter
      tags:
        - Player Character
      parameters:
        - name: playerCharacterId
          in: path
          required: true
          description: ID of the player character to get
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A player character
          content:
            application/json:
              schema:
                $ref: ./components/schemas/PlayerCharacter.yaml
  /roguish-feats:
    get:
      summary: Get all roguish feats
      operationId: listRougishFeats
      tags:
        - Roguish Feat
      responses:
        '200':
          description: A list of all roguish feats
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./components/schemas/RoguishFeat.yaml
  /roguish-feats/{roguishFeatId}:
    get:
      summary: Get a specific roguish feat by ID
      operationId: getRougishFeat
      tags:
        - Roguish Feat
      parameters:
        - name: roguishFeatId
          in: path
          required: true
          description: ID of the roguish feat to get
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A list of all roguish feats
          content:
            application/json:
              schema:
                $ref: ./components/schemas/RoguishFeat.yaml
  /equipment/:
    get:
      summary: Get all equipment
      operationId: listEquipment
      tags:
        - Equipment
      responses:
        '200':
          description: A list of all equipment
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./components/schemas/Equipment.yaml
  /equipment/{equipmentId}:
    get:
      summary: Get a specific equipment by ID
      operationId: getEquipment
      tags:
        - Equipment
      parameters:
        - name: equipmentId
          in: path
          required: true
          description: ID of the equipment to get
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A list of all equipment
          content:
            application/json:
              schema:
                $ref: ./components/schemas/Equipment.yaml