/* tslint:disable */
/* eslint-disable */
/**
 * Player Character API
 * This API definition describes a Player Character API. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: georgehbroadhurst@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Bonus
 */
export interface Bonus {
    /**
     * The unique identifier for a bonus
     * @type {string}
     * @memberof Bonus
     */
    'id'?: string;
    /**
     * The value of the bonus
     * @type {number}
     * @memberof Bonus
     */
    'value'?: number;
    /**
     * 
     * @type {Stat}
     * @memberof Bonus
     */
    'stat'?: Stat;
}
/**
 * 
 * @export
 * @interface Choice
 */
export interface Choice {
    /**
     * The unique identifier for a choice
     * @type {string}
     * @memberof Choice
     */
    'id'?: string;
    /**
     * The unique reference code for a choice
     * @type {string}
     * @memberof Choice
     */
    'referenceCode'?: string;
    /**
     * 
     * @type {ChoiceChoice}
     * @memberof Choice
     */
    'choice'?: ChoiceChoice;
}
/**
 * The chosen option
 * @export
 * @interface ChoiceChoice
 */
export interface ChoiceChoice {
    /**
     * The type of choice
     * @type {string}
     * @memberof ChoiceChoice
     */
    'choiceType'?: string;
    /**
     * 
     * @type {ChoiceChoiceResource}
     * @memberof ChoiceChoice
     */
    'resource'?: ChoiceChoiceResource;
}
/**
 * @type ChoiceChoiceResource
 * The resource of the choice
 * @export
 */
export type ChoiceChoiceResource = Bonus | Drive | Move | Nature | RoguishFeat | Skill;

/**
 * 
 * @export
 * @interface Drive
 */
export interface Drive {
    /**
     * The unique identifier for a drive
     * @type {string}
     * @memberof Drive
     */
    'id'?: string;
    /**
     * The unique code for a drive
     * @type {string}
     * @memberof Drive
     */
    'code'?: string;
    /**
     * The name of the drive
     * @type {string}
     * @memberof Drive
     */
    'name'?: string;
    /**
     * The description of the drive
     * @type {string}
     * @memberof Drive
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface Equipment
 */
export interface Equipment {
    /**
     * The unique identifier
     * @type {number}
     * @memberof Equipment
     */
    'id'?: number;
    /**
     * The name of the equipment
     * @type {string}
     * @memberof Equipment
     */
    'name'?: string;
    /**
     * The description of the equipment
     * @type {string}
     * @memberof Equipment
     */
    'description'?: string | null;
    /**
     * 
     * @type {Source}
     * @memberof Equipment
     */
    'source'?: Source;
    /**
     * The value of the equipment
     * @type {number}
     * @memberof Equipment
     */
    'value'?: number;
    /**
     * The load of the equipment
     * @type {number}
     * @memberof Equipment
     */
    'load'?: number;
    /**
     * The wear slots of the equipment
     * @type {number}
     * @memberof Equipment
     */
    'wearSlots'?: number;
    /**
     * 
     * @type {Array<EquipmentTag>}
     * @memberof Equipment
     */
    'tags'?: Array<EquipmentTag> | null;
    /**
     * 
     * @type {Array<Range>}
     * @memberof Equipment
     */
    'range'?: Array<Range> | null;
}
/**
 * 
 * @export
 * @interface Equipment1
 */
export interface Equipment1 {
    /**
     * The unique identifier for an equipment
     * @type {number}
     * @memberof Equipment1
     */
    'equipment_id'?: number;
    /**
     * The quantity of the equipment
     * @type {number}
     * @memberof Equipment1
     */
    'quantity'?: number;
    /**
     * The wear of the equipment
     * @type {number}
     * @memberof Equipment1
     */
    'wear'?: number;
}
/**
 * 
 * @export
 * @interface EquipmentTag
 */
export interface EquipmentTag {
    /**
     * The unique identifier for a equipment tag
     * @type {string}
     * @memberof EquipmentTag
     */
    'id'?: string;
    /**
     * The unique code for a equipment tag
     * @type {string}
     * @memberof EquipmentTag
     */
    'code'?: string;
    /**
     * The name of the equipment tag
     * @type {string}
     * @memberof EquipmentTag
     */
    'name'?: string;
    /**
     * The description of the equipment tag
     * @type {string}
     * @memberof EquipmentTag
     */
    'description'?: string;
    /**
     * Whether the equipment tag is positive or negative
     * @type {boolean}
     * @memberof EquipmentTag
     */
    'isPositive'?: boolean;
}
/**
 * 
 * @export
 * @interface Faction
 */
export interface Faction {
    /**
     * The unique identifier for a faction
     * @type {string}
     * @memberof Faction
     */
    'id'?: string;
    /**
     * The unique code for a faction
     * @type {string}
     * @memberof Faction
     */
    'code'?: string;
    /**
     * The name of the faction
     * @type {string}
     * @memberof Faction
     */
    'name'?: string;
    /**
     * The description of the faction
     * @type {string}
     * @memberof Faction
     */
    'description'?: string;
    /**
     * 
     * @type {Source}
     * @memberof Faction
     */
    'source'?: Source;
}
/**
 * 
 * @export
 * @interface Move
 */
export interface Move {
    /**
     * The unique identifier for a move
     * @type {string}
     * @memberof Move
     */
    'id'?: string;
    /**
     * The unique code for a move
     * @type {string}
     * @memberof Move
     */
    'code'?: string;
    /**
     * The name of the move
     * @type {string}
     * @memberof Move
     */
    'name'?: string;
    /**
     * The description of the move
     * @type {string}
     * @memberof Move
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface Nature
 */
export interface Nature {
    /**
     * The unique identifier for a drive
     * @type {string}
     * @memberof Nature
     */
    'id'?: string;
    /**
     * The unique code for a drive
     * @type {string}
     * @memberof Nature
     */
    'code'?: string;
    /**
     * The name of the drive
     * @type {string}
     * @memberof Nature
     */
    'name'?: string;
    /**
     * The description of the drive
     * @type {string}
     * @memberof Nature
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface Playbook
 */
export interface Playbook {
    /**
     * The unique identifier for a drive
     * @type {string}
     * @memberof Playbook
     */
    'id'?: string;
    /**
     * The unique code for a drive
     * @type {string}
     * @memberof Playbook
     */
    'code'?: string;
    /**
     * The name of the drive
     * @type {string}
     * @memberof Playbook
     */
    'name'?: string;
    /**
     * The description of the drive
     * @type {string}
     * @memberof Playbook
     */
    'description'?: string;
    /**
     * The natures of the drive
     * @type {Array<Nature>}
     * @memberof Playbook
     */
    'natures'?: Array<Nature>;
    /**
     * The moves of the drive
     * @type {Array<Move>}
     * @memberof Playbook
     */
    'moves'?: Array<Move>;
    /**
     * The drives of the drive
     * @type {Array<Drive>}
     * @memberof Playbook
     */
    'drives'?: Array<Drive>;
    /**
     * 
     * @type {Source}
     * @memberof Playbook
     */
    'source'?: Source;
    /**
     * 
     * @type {PlaybookSkills}
     * @memberof Playbook
     */
    'skills'?: PlaybookSkills;
    /**
     * The roguish feats of the drive
     * @type {Array<RoguishFeat>}
     * @memberof Playbook
     */
    'roguishFeats'?: Array<RoguishFeat>;
    /**
     * The starting value of the drive
     * @type {number}
     * @memberof Playbook
     */
    'startingValue'?: number;
    /**
     * The short description of the drive
     * @type {string}
     * @memberof Playbook
     */
    'shortDescription'?: string;
    /**
     * The long description of the drive
     * @type {string}
     * @memberof Playbook
     */
    'longDescription'?: string;
}
/**
 * The skills of the drive
 * @export
 * @interface PlaybookSkills
 */
export interface PlaybookSkills {
    /**
     * The charm skill of the drive
     * @type {number}
     * @memberof PlaybookSkills
     */
    'charm'?: number;
    /**
     * The cunning skill of the drive
     * @type {number}
     * @memberof PlaybookSkills
     */
    'cunning'?: number;
    /**
     * The finesse skill of the drive
     * @type {number}
     * @memberof PlaybookSkills
     */
    'finesse'?: number;
    /**
     * The luck skill of the drive
     * @type {number}
     * @memberof PlaybookSkills
     */
    'luck'?: number;
    /**
     * The might skill of the drive
     * @type {number}
     * @memberof PlaybookSkills
     */
    'might'?: number;
}
/**
 * 
 * @export
 * @interface PlayerCharacter
 */
export interface PlayerCharacter {
    /**
     * The unique identifier for a player character
     * @type {string}
     * @memberof PlayerCharacter
     */
    'id'?: string;
    /**
     * The name of the player character
     * @type {string}
     * @memberof PlayerCharacter
     */
    'name'?: string;
    /**
     * 
     * @type {PlayerCharacterStats}
     * @memberof PlayerCharacter
     */
    'stats'?: PlayerCharacterStats;
    /**
     * 
     * @type {Array<Move>}
     * @memberof PlayerCharacter
     */
    'moves'?: Array<Move>;
    /**
     * 
     * @type {Array<Nature>}
     * @memberof PlayerCharacter
     */
    'natures'?: Array<Nature>;
    /**
     * 
     * @type {Array<Drive>}
     * @memberof PlayerCharacter
     */
    'drives'?: Array<Drive>;
    /**
     * 
     * @type {Playbook}
     * @memberof PlayerCharacter
     */
    'playbook'?: Playbook;
    /**
     * 
     * @type {Array<Choice>}
     * @memberof PlayerCharacter
     */
    'choices'?: Array<Choice>;
    /**
     * 
     * @type {Array<Skill>}
     * @memberof PlayerCharacter
     */
    'skills'?: Array<Skill>;
    /**
     * 
     * @type {Array<RoguishFeat>}
     * @memberof PlayerCharacter
     */
    'roguishFeats'?: Array<RoguishFeat>;
    /**
     * 
     * @type {Array<Relationship>}
     * @memberof PlayerCharacter
     */
    'relationships'?: Array<Relationship>;
    /**
     * 
     * @type {Array<Equipment>}
     * @memberof PlayerCharacter
     */
    'equipment'?: Array<Equipment>;
}
/**
 * 
 * @export
 * @interface PlayerCharacterStats
 */
export interface PlayerCharacterStats {
    /**
     * The charm stat of the player character
     * @type {number}
     * @memberof PlayerCharacterStats
     */
    'charm'?: number;
    /**
     * The cunning stat of the player character
     * @type {number}
     * @memberof PlayerCharacterStats
     */
    'cunning'?: number;
    /**
     * The finesse stat of the player character
     * @type {number}
     * @memberof PlayerCharacterStats
     */
    'finesse'?: number;
    /**
     * The luck stat of the player character
     * @type {number}
     * @memberof PlayerCharacterStats
     */
    'luck'?: number;
    /**
     * The might stat of the player character
     * @type {number}
     * @memberof PlayerCharacterStats
     */
    'might'?: number;
}
/**
 * 
 * @export
 * @interface Range
 */
export interface Range {
    /**
     * The unique code for a equipment tag
     * @type {string}
     * @memberof Range
     */
    'code'?: string;
    /**
     * The name of the equipment tag
     * @type {string}
     * @memberof Range
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface Relationship
 */
export interface Relationship {
    /**
     * The unique identifier for a relationship
     * @type {string}
     * @memberof Relationship
     */
    'id'?: string;
    /**
     * 
     * @type {Faction}
     * @memberof Relationship
     */
    'faction'?: Faction;
    /**
     * The bonus of the relationship
     * @type {number}
     * @memberof Relationship
     */
    'bonus'?: number;
    /**
     * The prestige of the relationship
     * @type {number}
     * @memberof Relationship
     */
    'prestige'?: number;
    /**
     * The notoriety of the relationship
     * @type {number}
     * @memberof Relationship
     */
    'notoriety'?: number;
}
/**
 * 
 * @export
 * @interface RoguishFeat
 */
export interface RoguishFeat {
    /**
     * The unique identifier for a roguish feat
     * @type {string}
     * @memberof RoguishFeat
     */
    'id'?: string;
    /**
     * The unique code for a roguish feat
     * @type {string}
     * @memberof RoguishFeat
     */
    'code'?: string;
    /**
     * The name of the roguish feat
     * @type {string}
     * @memberof RoguishFeat
     */
    'name'?: string;
    /**
     * The description of the roguish feat
     * @type {string}
     * @memberof RoguishFeat
     */
    'description'?: string;
    /**
     * The risks of the roguish feat
     * @type {string}
     * @memberof RoguishFeat
     */
    'risks'?: string;
}
/**
 * 
 * @export
 * @interface Skill
 */
export interface Skill {
    /**
     * The unique identifier for a skill
     * @type {string}
     * @memberof Skill
     */
    'id'?: string;
    /**
     * The unique code for a skill
     * @type {string}
     * @memberof Skill
     */
    'code'?: string;
    /**
     * The name of the skill
     * @type {string}
     * @memberof Skill
     */
    'name'?: string;
    /**
     * The description of the skill
     * @type {string}
     * @memberof Skill
     */
    'description'?: string;
    /**
     * 
     * @type {Source}
     * @memberof Skill
     */
    'source'?: Source;
    /**
     * The type of the skill
     * @type {string}
     * @memberof Skill
     */
    'type'?: SkillTypeEnum;
}

export const SkillTypeEnum = {
    WeaponSkill: 'Weapon Skill'
} as const;

export type SkillTypeEnum = typeof SkillTypeEnum[keyof typeof SkillTypeEnum];

/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * The unique identifier for a source
     * @type {string}
     * @memberof Source
     */
    'id'?: string;
    /**
     * The unique code for a source
     * @type {string}
     * @memberof Source
     */
    'code'?: string;
    /**
     * The name of the source
     * @type {string}
     * @memberof Source
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface Stat
 */
export interface Stat {
    /**
     * The unique identifier for a stat
     * @type {string}
     * @memberof Stat
     */
    'id'?: string;
    /**
     * The unique code for a stat
     * @type {string}
     * @memberof Stat
     */
    'code'?: string;
    /**
     * The name of the stat
     * @type {string}
     * @memberof Stat
     */
    'name'?: string;
    /**
     * The description of the stat
     * @type {string}
     * @memberof Stat
     */
    'description'?: string;
    /**
     * The default value of the stat
     * @type {number}
     * @memberof Stat
     */
    'defaultValue'?: number;
}

/**
 * EquipmentApi - axios parameter creator
 * @export
 */
export const EquipmentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a specific equipment by ID
         * @param {string} equipmentId ID of the equipment to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEquipment: async (equipmentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'equipmentId' is not null or undefined
            assertParamExists('getEquipment', 'equipmentId', equipmentId)
            const localVarPath = `/equipment/{equipmentId}`
                .replace(`{${"equipmentId"}}`, encodeURIComponent(String(equipmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all equipment
         * @param {string} [search] Search term
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEquipment: async (search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/equipment/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EquipmentApi - functional programming interface
 * @export
 */
export const EquipmentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EquipmentApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a specific equipment by ID
         * @param {string} equipmentId ID of the equipment to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEquipment(equipmentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Equipment>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEquipment(equipmentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EquipmentApi.getEquipment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all equipment
         * @param {string} [search] Search term
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listEquipment(search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Equipment>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listEquipment(search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EquipmentApi.listEquipment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EquipmentApi - factory interface
 * @export
 */
export const EquipmentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EquipmentApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a specific equipment by ID
         * @param {string} equipmentId ID of the equipment to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEquipment(equipmentId: string, options?: RawAxiosRequestConfig): AxiosPromise<Equipment> {
            return localVarFp.getEquipment(equipmentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all equipment
         * @param {string} [search] Search term
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listEquipment(search?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Equipment>> {
            return localVarFp.listEquipment(search, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EquipmentApi - object-oriented interface
 * @export
 * @class EquipmentApi
 * @extends {BaseAPI}
 */
export class EquipmentApi extends BaseAPI {
    /**
     * 
     * @summary Get a specific equipment by ID
     * @param {string} equipmentId ID of the equipment to get
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentApi
     */
    public getEquipment(equipmentId: string, options?: RawAxiosRequestConfig) {
        return EquipmentApiFp(this.configuration).getEquipment(equipmentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all equipment
     * @param {string} [search] Search term
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EquipmentApi
     */
    public listEquipment(search?: string, options?: RawAxiosRequestConfig) {
        return EquipmentApiFp(this.configuration).listEquipment(search, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MoveApi - axios parameter creator
 * @export
 */
export const MoveApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a specific move by ID
         * @param {string} moveId ID of the move to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMove: async (moveId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'moveId' is not null or undefined
            assertParamExists('getMove', 'moveId', moveId)
            const localVarPath = `/moves/{moveId}`
                .replace(`{${"moveId"}}`, encodeURIComponent(String(moveId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all moves
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMoves: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/moves/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MoveApi - functional programming interface
 * @export
 */
export const MoveApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MoveApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a specific move by ID
         * @param {string} moveId ID of the move to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMove(moveId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Move>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMove(moveId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MoveApi.getMove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all moves
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMoves(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Move>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMoves(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MoveApi.listMoves']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MoveApi - factory interface
 * @export
 */
export const MoveApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MoveApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a specific move by ID
         * @param {string} moveId ID of the move to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMove(moveId: string, options?: RawAxiosRequestConfig): AxiosPromise<Move> {
            return localVarFp.getMove(moveId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all moves
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMoves(options?: RawAxiosRequestConfig): AxiosPromise<Array<Move>> {
            return localVarFp.listMoves(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MoveApi - object-oriented interface
 * @export
 * @class MoveApi
 * @extends {BaseAPI}
 */
export class MoveApi extends BaseAPI {
    /**
     * 
     * @summary Get a specific move by ID
     * @param {string} moveId ID of the move to get
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoveApi
     */
    public getMove(moveId: string, options?: RawAxiosRequestConfig) {
        return MoveApiFp(this.configuration).getMove(moveId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all moves
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoveApi
     */
    public listMoves(options?: RawAxiosRequestConfig) {
        return MoveApiFp(this.configuration).listMoves(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PlayerCharacterApi - axios parameter creator
 * @export
 */
export const PlayerCharacterApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add equipment to a specific player character
         * @param {string} playerCharacterId ID of the player character to add equipment to
         * @param {Equipment1} equipment1 Equipment object to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPlayerEquipment: async (playerCharacterId: string, equipment1: Equipment1, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playerCharacterId' is not null or undefined
            assertParamExists('addPlayerEquipment', 'playerCharacterId', playerCharacterId)
            // verify required parameter 'equipment1' is not null or undefined
            assertParamExists('addPlayerEquipment', 'equipment1', equipment1)
            const localVarPath = `/player-characters/{playerCharacterId}/equipment`
                .replace(`{${"playerCharacterId"}}`, encodeURIComponent(String(playerCharacterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(equipment1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a specific player character by ID
         * @param {number} playerCharacterId ID of the player character to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlayerCharacter: async (playerCharacterId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playerCharacterId' is not null or undefined
            assertParamExists('getPlayerCharacter', 'playerCharacterId', playerCharacterId)
            const localVarPath = `/player-characters/{playerCharacterId}`
                .replace(`{${"playerCharacterId"}}`, encodeURIComponent(String(playerCharacterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all player characters
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlayerCharacters: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/player-characters`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all equipment for a specific player character
         * @param {number} playerCharacterId ID of the player character to get equipment for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlayerEquipment: async (playerCharacterId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'playerCharacterId' is not null or undefined
            assertParamExists('listPlayerEquipment', 'playerCharacterId', playerCharacterId)
            const localVarPath = `/player-characters/{playerCharacterId}/equipment`
                .replace(`{${"playerCharacterId"}}`, encodeURIComponent(String(playerCharacterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlayerCharacterApi - functional programming interface
 * @export
 */
export const PlayerCharacterApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PlayerCharacterApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add equipment to a specific player character
         * @param {string} playerCharacterId ID of the player character to add equipment to
         * @param {Equipment1} equipment1 Equipment object to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addPlayerEquipment(playerCharacterId: string, equipment1: Equipment1, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Equipment>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addPlayerEquipment(playerCharacterId, equipment1, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlayerCharacterApi.addPlayerEquipment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a specific player character by ID
         * @param {number} playerCharacterId ID of the player character to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPlayerCharacter(playerCharacterId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlayerCharacter>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPlayerCharacter(playerCharacterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlayerCharacterApi.getPlayerCharacter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all player characters
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPlayerCharacters(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PlayerCharacter>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPlayerCharacters(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlayerCharacterApi.listPlayerCharacters']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all equipment for a specific player character
         * @param {number} playerCharacterId ID of the player character to get equipment for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPlayerEquipment(playerCharacterId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Equipment>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPlayerEquipment(playerCharacterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlayerCharacterApi.listPlayerEquipment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PlayerCharacterApi - factory interface
 * @export
 */
export const PlayerCharacterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PlayerCharacterApiFp(configuration)
    return {
        /**
         * 
         * @summary Add equipment to a specific player character
         * @param {string} playerCharacterId ID of the player character to add equipment to
         * @param {Equipment1} equipment1 Equipment object to add
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPlayerEquipment(playerCharacterId: string, equipment1: Equipment1, options?: RawAxiosRequestConfig): AxiosPromise<Array<Equipment>> {
            return localVarFp.addPlayerEquipment(playerCharacterId, equipment1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a specific player character by ID
         * @param {number} playerCharacterId ID of the player character to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlayerCharacter(playerCharacterId: number, options?: RawAxiosRequestConfig): AxiosPromise<PlayerCharacter> {
            return localVarFp.getPlayerCharacter(playerCharacterId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all player characters
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlayerCharacters(options?: RawAxiosRequestConfig): AxiosPromise<Array<PlayerCharacter>> {
            return localVarFp.listPlayerCharacters(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all equipment for a specific player character
         * @param {number} playerCharacterId ID of the player character to get equipment for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlayerEquipment(playerCharacterId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<Equipment>> {
            return localVarFp.listPlayerEquipment(playerCharacterId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PlayerCharacterApi - object-oriented interface
 * @export
 * @class PlayerCharacterApi
 * @extends {BaseAPI}
 */
export class PlayerCharacterApi extends BaseAPI {
    /**
     * 
     * @summary Add equipment to a specific player character
     * @param {string} playerCharacterId ID of the player character to add equipment to
     * @param {Equipment1} equipment1 Equipment object to add
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayerCharacterApi
     */
    public addPlayerEquipment(playerCharacterId: string, equipment1: Equipment1, options?: RawAxiosRequestConfig) {
        return PlayerCharacterApiFp(this.configuration).addPlayerEquipment(playerCharacterId, equipment1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a specific player character by ID
     * @param {number} playerCharacterId ID of the player character to get
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayerCharacterApi
     */
    public getPlayerCharacter(playerCharacterId: number, options?: RawAxiosRequestConfig) {
        return PlayerCharacterApiFp(this.configuration).getPlayerCharacter(playerCharacterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all player characters
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayerCharacterApi
     */
    public listPlayerCharacters(options?: RawAxiosRequestConfig) {
        return PlayerCharacterApiFp(this.configuration).listPlayerCharacters(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all equipment for a specific player character
     * @param {number} playerCharacterId ID of the player character to get equipment for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlayerCharacterApi
     */
    public listPlayerEquipment(playerCharacterId: number, options?: RawAxiosRequestConfig) {
        return PlayerCharacterApiFp(this.configuration).listPlayerEquipment(playerCharacterId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RoguishFeatApi - axios parameter creator
 * @export
 */
export const RoguishFeatApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get a specific roguish feat by ID
         * @param {string} roguishFeatId ID of the roguish feat to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getroguishFeat: async (roguishFeatId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roguishFeatId' is not null or undefined
            assertParamExists('getroguishFeat', 'roguishFeatId', roguishFeatId)
            const localVarPath = `/roguish-feats/{roguishFeatId}`
                .replace(`{${"roguishFeatId"}}`, encodeURIComponent(String(roguishFeatId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all roguish feats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listroguishFeats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/roguish-feats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoguishFeatApi - functional programming interface
 * @export
 */
export const RoguishFeatApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoguishFeatApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get a specific roguish feat by ID
         * @param {string} roguishFeatId ID of the roguish feat to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getroguishFeat(roguishFeatId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoguishFeat>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getroguishFeat(roguishFeatId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoguishFeatApi.getroguishFeat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all roguish feats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listroguishFeats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RoguishFeat>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listroguishFeats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoguishFeatApi.listroguishFeats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RoguishFeatApi - factory interface
 * @export
 */
export const RoguishFeatApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoguishFeatApiFp(configuration)
    return {
        /**
         * 
         * @summary Get a specific roguish feat by ID
         * @param {string} roguishFeatId ID of the roguish feat to get
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getroguishFeat(roguishFeatId: string, options?: RawAxiosRequestConfig): AxiosPromise<RoguishFeat> {
            return localVarFp.getroguishFeat(roguishFeatId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all roguish feats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listroguishFeats(options?: RawAxiosRequestConfig): AxiosPromise<Array<RoguishFeat>> {
            return localVarFp.listroguishFeats(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoguishFeatApi - object-oriented interface
 * @export
 * @class RoguishFeatApi
 * @extends {BaseAPI}
 */
export class RoguishFeatApi extends BaseAPI {
    /**
     * 
     * @summary Get a specific roguish feat by ID
     * @param {string} roguishFeatId ID of the roguish feat to get
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoguishFeatApi
     */
    public getroguishFeat(roguishFeatId: string, options?: RawAxiosRequestConfig) {
        return RoguishFeatApiFp(this.configuration).getroguishFeat(roguishFeatId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all roguish feats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoguishFeatApi
     */
    public listroguishFeats(options?: RawAxiosRequestConfig) {
        return RoguishFeatApiFp(this.configuration).listroguishFeats(options).then((request) => request(this.axios, this.basePath));
    }
}



